# Generated by Django 2.1 on 2019-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mail', models.EmailField(max_length=254)),
                ('to_mail', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=25)),
                ('to_name', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
